options:
  extra-pip-packages:
    type: string
    default: ""
    description: |
      Space separated list of extra packages to `pip install`
  http-proxy:
    type: string
    description: |
      http_proxy setting for installing from PyPI
  https-proxy:
    type: string
    description: |
      https_proxy setting for installing from PyPI
  jupyter-base-url:
    description: |
      Base URL of the notebook, if reverse-proxied
    type: string
  jupyter-web-password:
    description: |
      Jupyter web password - if not set, this charm will generate a password for you and expose it via web ui.
    type: string
    default: ""
  jupyter-web-port:
    description: |
      TCP web port for Jupyter notebook
    type: int
    default: 9999
